import { Eye, EyeSlash, Fingerprint, ArrowUpRight, Info } from '@phosphor-icons/react';
import { Surface } from './Primitives';

export function Privacy() {
  return <section className="privacy-view reveal"><div className="section-intro"><span className="eyebrow">Selective disclosure</span><h1>Less revealed.<br />More protected.</h1><p>A valid invitation is all the event needs to know. Here’s exactly where Veil’s privacy begins and ends.</p></div>
    <div className="privacy-grid"><Surface><EyeSlash size={28} weight="light" /><h2>Kept out of the public proof.</h2><ul className="privacy-list"><li>Your private invitation secret</li><li>Which allowlist entry you used</li><li>Your private membership path</li></ul><p className="muted">Veil does not ask for your name, email or identity documents.</p></Surface><Surface><Eye size={28} weight="light" /><h2>Visible on the network.</h2><ul className="privacy-list"><li>The event and its allowlist commitments</li><li>A one-time identifier that prevents reuse</li><li>Admission counts and transaction timing</li></ul><p className="muted">Successful membership verification is public. The underlying invitation remains hidden.</p></Surface></div>
    <div className="privacy-explainer"><Fingerprint size={40} weight="light" /><div><h2>Prove you belong. Keep your invitation.</h2><p>A zero-knowledge circuit checks your invitation against a fixed Merkle root. A separate identifier, called a nullifier, makes each invitation usable once. The contract checks the witness itself, so a modified app cannot substitute somebody else’s membership path.</p></div></div>
    <Surface className="trust-boundary"><div className="inline-label"><Info size={20} weight="light" /><h2>The honest boundaries.</h2></div><div className="boundary-grid"><p><strong>The organizer.</strong> An organizer who creates your secret can correlate your admission. Veil does not promise anonymity from that organizer.</p><p><strong>Your device.</strong> Secrets stay in this tab and your local proof server. A compromised device or browser extension may expose them.</p><p><strong>The crowd.</strong> Small guest lists and transaction timing can create correlations. Privacy improves with a larger anonymity set.</p><p><strong>Your invitation.</strong> It is a bearer credential. Anyone with its secret can redeem it first. Share it only with the intended guest.</p></div></Surface>
    <a className="external-link" href="https://docs.midnight.network/concepts/how-midnight-works/keeping-data-private" target="_blank" rel="noopener noreferrer">Explore Midnight’s privacy model <ArrowUpRight size={18} weight="light" aria-hidden="true" /></a>
  </section>;
}
